################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Drivers/BSP/Components/adv7533 \
Drivers/BSP/Components/exc7200 \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/Components/ft6x06 \
Drivers/BSP/Components/mfxstm32l152 \
Drivers/BSP/Components/otm8009a \
Drivers/BSP/Components/ov9655 \
Drivers/BSP/Components/s5k5cag \
Drivers/BSP/Components/st7735 \
Drivers/BSP/Components/st7789h2 \
Drivers/BSP/Components/stmpe811 \
Drivers/BSP/Components/ts3510 \
Drivers/BSP/Components/wm8994 \
Drivers/BSP/STM32F769I-Discovery \
Drivers/STM32F7xx_HAL_Driver/Src \
Src \
Utilities/Fonts \
lv_examples/lv_apps/benchmark \
lv_examples/lv_apps/demo \
lv_examples/lv_apps/sysmon \
lv_examples/lv_apps/terminal \
lv_examples/lv_apps/tpcal \
lv_examples/lv_tests/lv_test_group \
lv_examples/lv_tests/lv_test_misc \
lv_examples/lv_tests/lv_test_obj \
lv_examples/lv_tests/lv_test_objx/lv_test_bar \
lv_examples/lv_tests/lv_test_objx/lv_test_btn \
lv_examples/lv_tests/lv_test_objx/lv_test_btnm \
lv_examples/lv_tests/lv_test_objx/lv_test_cb \
lv_examples/lv_tests/lv_test_objx/lv_test_chart \
lv_examples/lv_tests/lv_test_objx/lv_test_cont \
lv_examples/lv_tests/lv_test_objx/lv_test_ddlist \
lv_examples/lv_tests/lv_test_objx/lv_test_gauge \
lv_examples/lv_tests/lv_test_objx/lv_test_img \
lv_examples/lv_tests/lv_test_objx/lv_test_kb \
lv_examples/lv_tests/lv_test_objx/lv_test_label \
lv_examples/lv_tests/lv_test_objx/lv_test_led \
lv_examples/lv_tests/lv_test_objx/lv_test_line \
lv_examples/lv_tests/lv_test_objx/lv_test_list \
lv_examples/lv_tests/lv_test_objx/lv_test_lmeter \
lv_examples/lv_tests/lv_test_objx/lv_test_mbox \
lv_examples/lv_tests/lv_test_objx/lv_test_page \
lv_examples/lv_tests/lv_test_objx/lv_test_roller \
lv_examples/lv_tests/lv_test_objx/lv_test_slider \
lv_examples/lv_tests/lv_test_objx/lv_test_sw \
lv_examples/lv_tests/lv_test_objx/lv_test_ta \
lv_examples/lv_tests/lv_test_objx/lv_test_tabview \
lv_examples/lv_tests/lv_test_objx/lv_test_win \
lv_examples/lv_tests/lv_test_stress \
lv_examples/lv_tests/lv_test_theme \
lv_examples/lv_tutorial/0_porting \
lv_examples/lv_tutorial/10_keyboard \
lv_examples/lv_tutorial/1_hello_world \
lv_examples/lv_tutorial/2_objects \
lv_examples/lv_tutorial/3_styles \
lv_examples/lv_tutorial/4_themes \
lv_examples/lv_tutorial/5_antialiasing \
lv_examples/lv_tutorial/6_images \
lv_examples/lv_tutorial/7_fonts \
lv_examples/lv_tutorial/8_animations \
lv_examples/lv_tutorial/9_responsive \
lvgl/lv_core \
lvgl/lv_draw \
lvgl/lv_hal \
lvgl/lv_misc \
lvgl/lv_misc/lv_fonts \
lvgl/lv_objx \
lvgl/lv_themes \
startup \

